[
    {
        "email": "Ive uploaded more markups here: Please complete drafting for 23-043 before moving on to this project. Please also print the current arch set (plan sheets only) from the latest arch model.",
        "score": 0.4
    },
    {
        "email": "Hi Arthur,The updated pdf set is attached here for your review. Also, I would like to inform you that we have considered the revision \"delta 1\" as \"MR1\" as we have replaced all \"delta 1\" revisions with new \"MR1\" revision on 14th May, as per your instruction. Please let us know if our understanding is wrong.",
        "score": 0.6
    },
    {
        "email": "Arghya,Please respond to the discrepancy raised by our HVAC sub regarding the Louver size.",
        "score": -1.0
    },
    {
        "email": "Per our process, did you update Autodesk Construction Cloud too? After our meeting Friday, we may need to update the shop drawings once coordination effort is done. Aaron Wright",
        "score": 0.5
    },
    {
        "email": "Hi Deepak,Let me know if you received the email below.Very Respectfully,Abraham Canlas",
        "score": 0.8
    },
    {
        "email": "Hi Sanjib,Please provide update.Thank you.Very Respectfully,Abraham Canlas",
        "score": 0.5
    },
    {
        "email": "Sunil,See attached with comments.Thanks.Very Respectfully,Abraham Canlas",
        "score": 0.6
    },
    {
        "email": "Currently the Light Pole Bases for DC4 are not included in CSIs scope of work. Is this something the Clayco team would want us to start pricing? If so, a takeoff depicting which Light Pole Bases are included in the DC4 scope would greatly assist with this if needed. Thanks, Luke",
        "score": 0.0
    },
    {
        "email": "Rahul,I can",
        "score": -0.1
    },
    {
        "email": ", ",
        "score": 0.3
    },
    {
        "email": "t have updated model but they have updated drawings saved in here, please correct the HVAC drawings based on the comments about not using the most updated Arch drawings.",
        "score": -0.2
    },
    {
        "email": "Good day. Please do the needful. We cannot send an ambulance at the moment as one of our ambulance is with the patient at National Care Hospital and we need an ambulance standby at the site",
        "score": 0.3
    },
    {
        "email": "Per process, update Autodesk Construction Cloud too? meeting Friday, may need update shop drawings coordination effort done. Aaron Wright",
        "score": 0.5
    },
    {
        "email": "Let know received email below. Respectfully, Abraham Canlas Engineer III GRANITE CONSTRUCTION COMPANY GUAM 425 Chalan San Antonio PMB 1022 Tamuning, GU 96913",
        "score": 0.8
    },
    {
        "email": "Please provide update. Thank you. Respectfully, Abraham Canlas",
        "score": 0.5
    },
    {
        "email": "Sunil, See attached comments. Thanks. Respectfully, Abraham Canlas Engineer III GRANITE CONSTRUCTION COMPANY GUAM 425 Chalan San Antonio PMB 1022 Tamuning, GU 96913",
        "score": 0.6
    },
    {
        "email": "Classification | Internal *Noted.* Dear Ramakant, FYI *Driver-Isha-0509324047*",
        "score": 0.0
    },
    {
        "email": "Classification | Internal *REMINDER * URGENTLY NEEDED COMPLETE SHEET *From:* Afzal Ahmed Farooqui",
        "score": 0.1
    },
    {
        "email": "Ive uploaded more markups here: Please complete drafting 23-043 moving project. Please also print current arch set (plan sheets only) latest arch model. Thanks, Arthur Cao, SE Senior Engineer FORELL | ELSESSER D: 415 248 3027 | E: <mailto:> | W: forell.com< FORELL ELSESSER achieved label. Learn here: FORELL + Just<",
        "score": 0.4
    },
    {
        "email": "Hi Sam, I",
        "score": 0.6
    },
    {
        "email": ", ",
        "score": -1.0
    },
    {
        "email": ", ",
        "score": 0.5
    },
    {
        "email": ", ",
        "score": 0.8
    },
    {
        "email": ", ",
        "score": 0.5
    },
    {
        "email": ", ",
        "score": 0.6
    },
    {
        "email": "Currently the Light Pole Bases DC4 included CSIs scope work. something Clayco team would want us start pricing? so, takeoff depicting Light Pole Bases included DC4 scope would greatly assist needed. Thanks, Luke",
        "score": 0.0
    },
    {
        "email": "Rahul, I can",
        "score": -0.1
    },
    {
        "email": ", ",
        "score": 0.3
    },
    {
        "email": "t updated model updated drawings saved here, please correct hvac drawings based comments using updated Arch drawings.",
        "score": -0.2
    },
    {
        "email": "Classification | Internal *Noted.* Dear Ramakant, FYI *Driver-Isha-0509324047*",
        "score": 0.3
    }
]